### PR TITLE
[READY] Landingpage

### PR DESCRIPTION
**Pull request by sn3p**
Fixing https://github.com/DefactoSoftware/PickupGameBot/issues/19

- [x] Stats on landingpage
- [x] Credits and Github links
- [x] Repsponsive styling
- [x] i18n strings

### CODE REVIEW

**Comment by dkhgh** [comment]
Omg

**Comment by dkhgh** [comment]
* [ ] screenshot? 🍀

**Comment by sn3p** [comment]
Was already on it 👊

**Comment by dkhgh** [comment]
Supernice!

Maybe also mention Zerocopter since you and Jurre are involved? Also, if you pass 'count: Player.count' with your i18n you can do:

'''Yml
Players:
  One: Player
  Other: Players
'''

(Markup may be fucked. I'm on my phone)

**Comment by sn3p** [comment]
Good idea, will add Jurre.
Ah yes forgot to do pluralization, will add now.

**Comment by sn3p** [comment]
@jurre which one do you prefer?

screen shot 2016-05-14 at 20 02 54

screen shot 2016-05-14 at 20 03 56

**Comment by jurre** [comment]
Zerocopter is 👍 

And super nice!

**Comment by sn3p** [comment]
Ait, done.

**Pull request merged**
